version: '3'
services:
  sorryweb:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - sorrydb
  sorrydb:
    image: postgres:latest
    environment:
      POSTGRES_DB: sorryjar_db
      POSTGRES_USER: sorryuser
      POSTGRES_PASSWORD: sorrypassword
