# Generated by Django 5.1.2 on 2024-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorrycount',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='sorrycount',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sorrycount',
            name='user',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
